models = [ "tam", "tvm", "cdm", "bdr", "mdr" ]

[paths.tide]
tam = "Models/Threat Actor Models/"
tvm = "Models/Threat Vector Models/"
cdm = "Models/Cyber Detection Models/"
mdr = "Models/Managed Detection Rules/"
bdr = "Models/Business Detection Requests/"
reports = "Reports/"
lookups = "Lookups/"
analytics = "Analytics/"
snippet_file = ".vscode/Model Templates.code-snippets"
json_schemas = "Schemas/"
templates = "Schemas/Templates/"
custom_configurations = "Configurations/"

[paths.core]
staging_index_output = "staging_index.json"
index_output = "index.json"
vocabularies = "Framework/Vocabulary/"
configurations = "Configurations/"
metaschemas = "Framework/Meta Schemas/"
subschemas = "Framework/Meta Schemas/Sub Schemas/"
definitions = "Framework/Meta Schemas/Definitions/"
wiki_docs_folder = "wiki/"
models_docs_folder = "wiki/Knowledge Graph/"
lookup_docs = "wiki/Lookups/"
schemas_docs_folder = "wiki/Specifications/"
vocabularies_docs = "wiki/Vocabularies/"
resources = "External/"

[metaschemas]
tam = "TAM Meta Schema.yaml"
tvm = "TVM Meta Schema.yaml"
cdm = "CDM Meta Schema.yaml"
mdr = "MDR Meta Schema.yaml"
mdrv2 = "MDRv2 Meta Schema.yaml"
bdr = "BDR Meta Schema.yaml"
lookup_metadata = "Lookup Metadata Meta Schema.yaml"

[recomposition]
systems = "MDR Systems Deployment"

[json_schemas]
tam = "TAM Schema.json"
tvm = "TVM Schema.json"
cdm = "CDM Schema.json"
mdr = "MDR Schema.json"
bdr = "BDR Schema.json"
lookup_metadata = "Lookup Metadata Schema.json"

[models_vocabularies]
tam = "Threat Actors.yaml"
tvm = "Threat Vectors.yaml"
cdm = "Detection Models.yaml"
bdr = "Detection Models.yaml"

[datafields]
tam = "actor"
tvm = "threat"
cdm = "detection"
mdr = "rule"
bdr = "request"

[templates]
tam = "TAM TEMPLATE.yaml"
tvm = "TVM TEMPLATE.yaml"
cdm = "CDM TEMPLATE.yaml"
mdr = "MDR TEMPLATE.yaml"
bdr = "BDR TEMPLATE.yaml"
lookup_metadata = "LOOKUP METADATA TEMPLATE.yaml"
