name: Data Classification Marking
field: classification
description: Information Security classification for the data contained within the TIDeMEC object.
reference:
  - https://www.consilium.europa.eu/en/general-secretariat/corporate-policies/classified-information/
  - https://www.northropgrumman.com/wp-content/uploads/NATORefresherBriefing.pdf
icon: 💡

stages:
  - id: EUCI
    name: European Union Classified Information 
    icon: 💶
    description: |
      In order for the Council to be able to work in all areas which require the use of EU classified information (EUCI),
      it needs to have a comprehensive security system to protect this information. The Council decision on the security
      rules for protecting EU classified information lays down the basic principles and minimum standards of security for
      protecting EUCI. These principles and standards apply to the Council and its General Secretariat, and they also need
      to be respected by member states when they handle EUCI.

      EU classified information is categorised into 4 levels which are defined by the severity of the impact of disclosure.
    link: https://www.consilium.europa.eu/en/general-secretariat/corporate-policies/classified-information/ 
  - id: NATO
    name: NATO CLASSIFICATION MARKINGS
    icon: 🪖
    description: |
      NATO information is information that has been generated by or for NATO, or member nation 
      originated-information that has been released into the NATO security system. Information marked 
      “NATO” is the property of NATO. NATO classified information contributed by a member nation 
      remains the property of the originating nation, even though it is circulated in a document belonging 
      to NATO.
    link: https://wpcontent.ot5o9s93syrb.net/wp-content/uploads/NATORefresherBriefing.pdf

keys:
  ####################European Union Classified Information####################
  - id: DCM0001
    name: RESTREINT UE/EU RESTRICTED
    tide.vocab.stages: EUCI
    description: The unauthorised disclosure of this information could be disadvantageous to the interests of the EU or one or more of the member states.
  - id: DCM0002
    name: CONFIDENTIEL UE/EU CONFIDENTIAL
    tide.vocab.stages: EUCI
    description: The unauthorised disclosure of this information could cause exceptionally grave prejudice to the essential interests of the EU or one or more of the member states.
  - id: DCM0003
    name: SECRET UE/EU SECRET
    tide.vocab.stages: EUCI
    description: The unauthorised disclosure of this information could seriously harm the essential interests of the EU or one or more of the member states.
  - id: DCM0004
    name: TRÈS SECRET UE/EU TOP SECRET
    tide.vocab.stages: EUCI
    description: The unauthorised disclosure of this information could cause exceptionally grave prejudice to the essential interests of the EU or one or more of the member states.
  #########################NATO CLASSIFICATION MARKINGS#########################
  - id: DCM0006
    name: NATO Unclassified 
    tide.vocab.stages: NATO
    description: |
      This is applied to official information that is the property of NATO but 
      does not meet the criteria for classification. Access to this information 
      by non-NATO entities is permitted when such access would not be 
      detrimental to NATO.
  - id: DCM0007
    name: NATO RESTRICTED 
    tide.vocab.stages: NATO
    description: |
      Applied to information whose unauthorized disclosure would be 
      disadvantageous to the interests of NATO. Though similar safeguards 
      are applied to FOR OFFICIAL USE ONLY, OFFICIAL USE ONLY, or 
      SENSITIVE, BUT UNCLASSIFIED information, NATO RESTRICTED 
      is a security classification.
  - id: DCM0008
    name: NATO CONFIDENTIAL
    tide.vocab.stages: NATO
    description: |
      Applied to information whose unauthorized disclosure would be 
      damaging to NATO interests.
  - id: DCM0009
    name: NATO CONFIDENTIAL ATOMAL
    tide.vocab.stages: NATO
    description: |
      Applied to information whose unauthorized disclosure would be 
      damaging to NATO interests.

      This designation is added to the NATO security classification when 
      applicable. For example, COSMIC TOP SECRET ATOMAL (CTS-A).
      ATOMAL information applies to U.S. RESTRICTED DATA or 
      FORMERLY RESTRICTED DATA or United Kingdom Atomic 
      Information released to NATO. 
  - id: DCM0010
    name: NATO SECRET
    tide.vocab.stages: NATO
    description: |
      Applied to information whose unauthorized disclosure would cause 
      serious damage to NATO.
  - id: DCM0011
    name: NATO SECRET ATOMAL
    tide.vocab.stages: NATO
    description: |
      Applied to information whose unauthorized disclosure would cause 
      serious damage to NATO.

      This designation is added to the NATO security classification when 
      applicable. For example, COSMIC TOP SECRET ATOMAL (CTS-A).
      ATOMAL information applies to U.S. RESTRICTED DATA or 
      FORMERLY RESTRICTED DATA or United Kingdom Atomic 
      Information released to NATO. 
  - id: DCM0012
    name: COSMIC TOP SECRET
    tide.vocab.stages: NATO
    description: |
      Applied to information whose unauthorized disclosure would cause 
      exceptionally grave damage to NATO. COSMIC is applied to Top 
      Secret material to signify it belongs to NATO. The term NATO TOP 
      SECRET is not used.
  - id: DCM0013
    name: COSMIC TOP SECRET ATOMAL
    tide.vocab.stages: NATO
    description: |
      Applied to information whose unauthorized disclosure would cause 
      exceptionally grave damage to NATO. COSMIC is applied to Top 
      Secret material to signify it belongs to NATO. The term NATO TOP 
      SECRET is not used.

      This designation is added to the NATO security classification when 
      applicable. For example, COSMIC TOP SECRET ATOMAL (CTS-A).
      ATOMAL information applies to U.S. RESTRICTED DATA or 
      FORMERLY RESTRICTED DATA or United Kingdom Atomic 
      Information released to NATO. 