stages:
  - debug
  - 📝 Reporting
  - 🧬 Mutation
  - ✅ Validation
  - 📖 Documentation
  - 🗿 Framework
  - 🚀 Deployment

include: 
  - local: '/Pipelines/Gitlab/modules/reporting.yml'
  - local: '/Pipelines/Gitlab/modules/mutation.yml'
  - local: '/Pipelines/Gitlab/modules/validation.yml'
  - local: '/Pipelines/Gitlab/modules/documentation.yml'
  - local: '/Pipelines/Gitlab/modules/framework.yml'
  - local: '/Pipelines/Gitlab/modules/deployment.yml'