# This file contains the remote imports to this repository, required when coretide
# is consumed in a remote mode. This allows a single entry point to coretide.

stages:
  - 📝 Reporting
  - 🧬 Mutation
  - ✅ Validation
  - 📖 Documentation
  - 🗿 Framework
  - 🚀 Deployment

include: 
  - remote: 'https://code.europa.eu/ec-digit-s2/opentide/coretide/-/raw/core/Pipelines/Gitlab/modules/deployment.yml'
  - remote: 'https://code.europa.eu/ec-digit-s2/opentide/coretide/-/raw/core/Pipelines/Gitlab/modules/documentation.yml'
  - remote: 'https://code.europa.eu/ec-digit-s2/opentide/coretide/-/raw/core/Pipelines/Gitlab/modules/framework.yml'
  - remote: 'https://code.europa.eu/ec-digit-s2/opentide/coretide/-/raw/core/Pipelines/Gitlab/modules/mutation.yml'
  - remote: 'https://code.europa.eu/ec-digit-s2/opentide/coretide/-/raw/core/Pipelines/Gitlab/modules/reporting.yml'
  - remote: 'https://code.europa.eu/ec-digit-s2/opentide/coretide/-/raw/core/Pipelines/Gitlab/modules/validation.yml'
